### ISSUE TITLE
If language WIT is not english codepage

### ISSUE THREAD

**Issue by ikhudorozhkov** [Microsoft/process-customization-scripts#11]
script is fall:

![image](https://user-images.githubusercontent.com/31690100/42095419-3ea4ce1e-7bbb-11e8-91df-ec3675176d46.png)

`$encoding = [System.Text.Encoding]::UTF8`
Dont fix it. 

Please halp :)

**Comment by aprilix** [comment]
I have WIT named in russian. So:
> Invoke-Expression "& $WitAdminExe listwitd /collection:$CollectionURL /p:`"$ProjectName`""
returns something like:
... 
**Задача** // it's look ok
...

but
> Invoke-Expression "& $WitAdminExe listwitd /collection:$CollectionURL /p:`"$ProjectName`"" | % { Write-Host $_ }
returns: 
...
**??????** //something goes wrong...
...

It look like problem with encodings. Please look at line 190 in ExportProjectTemplate.ps1 file.

**Comment by danhellem** [comment]
only english is supported in these scripts...no plans to make them work with other languages
