### ISSUE TITLE
future roadmap of process customization scripts

### ISSUE THREAD

**Issue by FrancescoSclano** [Microsoft/process-customization-scripts#19]
I'd like to know if https://github.com/microsoft/process-customization-scripts is compatible/properly working with Visual Studio 2019 libraries released by Microsoft on May 24th 2019 ? In other words, will these scripts work with DevOps 2020? Will these scripts be replaced by some other new scripts or by some new integrated functionality in DevOps 2020? 
In essence I'd like to know the future roadmap of these scripts.

Thanks

Francesco Sclano

**Comment by danhellem** [comment]
The scripts will still work in 2020. Only some minor changes. I will try and pull the latest XML files from server and post here.

**Comment by kostukp96** [comment]
can you added latest xml files ?

**Comment by danhellem** [comment]
yeah it's on my to-do list. Will work on that

**Comment by danhellem** [comment]
Done, thanks to @omarv74
