### ISSUE TITLE
Add Import/Export FieldMapping.xml

### ISSUE THREAD

**Issue by nschonni** [Microsoft/process-customization-scripts#3]
This likely also doesn't apply to the VSTS, but this can be done with
**Export**

```
TfsFieldMapping  download /collection:$CollectionUrl /teamproject:"$ProjectName" /mappingfile:"$tempFile"
```

**Import**

```
tfsFieldmapping  upload /collection:$CollectionUrl /teamproject:"$ProjectName" /mappingfile:"$outPath"
```

Similar logic to the `witadmin.exe` lookup would need to be added, so i'll see if you're interested in this before PR'ing something.

**Comment by danhellem** [comment]
what is the reason for doing a mapping in this scenario?

**Comment by nschonni** [comment]
It's used by the Project Server integration https://msdn.microsoft.com/en-us/library/gg412643%28v=vs.120%29.aspx
This might not be applicable to the VSTS instances, but it is a part of the Process Template

**Comment by FokkoVeegens** [comment]
The support for this integration is discontinued for newer versions of TFS: https://blogs.msdn.microsoft.com/visualstudioalm/2016/09/16/microsoft-discontinuing-project-server-tfs-integration/
