### ISSUE TITLE
Project export failed error

### ISSUE THREAD

**Issue by habhishek** [Microsoft/process-customization-scripts#6]
I was trying this script to export templates from an on-prem TFS collection. I am able to export templates from one project but unable to do that from another project in the same collection.

Getting "Project export failed" after the Step1 output.

Please help!

**Comment by danhellem** [comment]
The best thing to do is to comment out the [try statement](https://github.com/Microsoft/process-customization-scripts/blob/master/Export/ExportProjectTemplate.ps1#L111) so you can get the real error. If you still have issues let me know and help you dig into it.

**Comment by habhishek** [comment]
Yeah...I figured that out after some time. I found that it was looking for a SharePoint sample document which probably does not exist in some projects. I realized I don't need SharePoint XML and docs at this point so I just removed that folder which skips looking for that. And I must say, that it's a great script!

**Comment by danhellem** [comment]
Awesome. Glad you are unblocked. I will close out the issue.
