### ISSUE TITLE
Path to witadmin is limited to Enterprise version only.

### ISSUE THREAD

**Issue by jimbuck** [Microsoft/process-customization-scripts#8]
I installed Visual Studio 2017 Team Viewer (as recommended on the website) and it couldn't find it. I also installed Visual Studio 2017 Professional (according to my MSDN license) and it couldn't find it. Once I change the word "Enterprise" to "Professional" it worked like a charm. Would a PR that adds checks in multiple tiers be welcomed in this case?

https://github.com/Microsoft/process-customization-scripts/blob/837816848374c4b8ef7802c4d790a95a0482026f/Import/ConformProject.ps1#L26-L31

**Comment by danhellem** [comment]
Yeah feel free to create PR for this work. Good find!

**Comment by lukeschlather** [comment]
Hey I added a fix, if someone could merge. It's a trivial change.

**Comment by danhellem** [comment]
This should be fixed with the merge from #8
