### ISSUE TITLE
Multiple template failures due to: The 'refname' attribute is not declared.

### ISSUE THREAD

**Issue by ghost** [Microsoft/process-customization-scripts#9]
Are these templates for TFS2015, or TFS2018?  If they're TFS2015, then they are absolutely useless when performing upgrades.  FYI, the official Microsoft documentation points to this repo:

https://docs.microsoft.com/en-us/vsts/articles/migration-processtemplates?view=vsts

Here is the results when I try to force a project to be Agile:

Unable to find witadmin.exe on your path. Attempting VS install directories
Testing for C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\witadmin.exe
Testing for C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\witadmin.exe
Testing for C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\witadmin.exe
Testing for C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\witadmin.exe
Step 1: Preparing Conform
Operation Complete
Step 1: Complete
Step 2: Validating Work Items
Work Item Type SharedStep.xml missing from the project, it will be added in Step 5
Step 2: Complete
Step 3: Conform project - Link Types
Importing Link Type:  SharedParameterLink.xml
The link types were imported successfully.
Importing Link Type:  SharedStep.xml
The link types were imported successfully.
Importing Link Type:  TestedBy.xml
The link types were imported successfully.
Step 3: Complete
Step 4: Conform project - Type Definitions
Importing Work Item Type:  Bug.xml
TF212019: Work item tracking schema validation error at row 3, column 28: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 861, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  CodeReviewRequest.xml
TF212019: Work item tracking schema validation error at row 3, column 44: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 287, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  CodeReviewResponse.xml
TF212019: Work item tracking schema validation error at row 3, column 45: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 327, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  Epic.xml
TF212019: Work item tracking schema validation error at row 3, column 29: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 511, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  Feature.xml
TF212019: Work item tracking schema validation error at row 3, column 32: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 511, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  FeedbackRequest.xml
TF212019: Work item tracking schema validation error at row 3, column 41: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 215, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  FeedbackResponse.xml
TF212019: Work item tracking schema validation error at row 3, column 42: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 207, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  Issue.xml
TF212019: Work item tracking schema validation error at row 3, column 30: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 250, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  SharedParameter.xml
TF212019: Work item tracking schema validation error at row 3, column 41: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 171, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  SharedStep.xml
TF212019: Work item tracking schema validation error at row 3, column 37: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 248, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  Task.xml
TF212019: Work item tracking schema validation error at row 3, column 29: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 395, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  TestCase.xml
TF212019: Work item tracking schema validation error at row 3, column 34: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 343, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  TestPlan.xml
TF212019: Work item tracking schema validation error at row 3, column 34: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 143, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  TestSuite.xml
TF212019: Work item tracking schema validation error at row 3, column 35: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 189, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Importing Work Item Type:  UserStory.xml
TF212019: Work item tracking schema validation error at row 3, column 35: The 'refname' attribute is not declared.
TF212019: Work item tracking schema validation error at row 545, column 8: The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.
TF237070: Importing the definition failed. The definition you are trying to import did not validate against the schema. Edit the definition, then try to import it again.
Step 4: Complete
Step 5: Conform project - Categories
The category import has completed.
Step 5: Complete
Step 6: Conform project - Process Configuration
Microsoft (R) Work Item Tracking Administration tool.
Copyright (c) Microsoft Corporation. All rights reserved.
TF212001: importprocessconfig is not a witadmin command. Type 'witadmin' and press Enter for a list of commands.
Step 6: Complete
Project 'Client Projects' conforms to the template

**Comment by nschonni** [comment]
Sounds like it might be related to the script only finding an old version of witadmin (VS 2010?) like #8 if you're not running 2017 Enterprise.

> The element 'FORM' has invalid child element 'WebLayout'. List of possible elements expected: 'Layout'.

Is something I've seen before when the first witadmin in my path was for VS 2013/2015

**Comment by omarv74** [comment]
Kaelum,

Would you mind sharing the parameters you are passing? I just ran the script about a week and a half ago, also conforming Team Projects to Agile and the only issue I had was the one you got on Step 2, which is a very easy fix (Rename SharedStep.xml to SharedSteps.xml and make sure you do the same within WorkItems.xml). 

I am curious about your script parameters because I just looked at the Agile Bug.xml included in this repo, more specifically, at the line that your error message states that 'refname' is not declared and it is actually, there (last commit April/19). Is there a chance that your script may be picking up a different template for some reason?

**Comment by ghost** [comment]
I am running this against the latest version of TFS 2018 on premises.  The parameters are very simple, using exactly what the docs state.  I have to remove certain information though:

`.\ConformProject.ps1 "http://<tfs server>:8080/DefaultCollection" "<project name>" "<path>\Import\Agile"`

Prior to migrating to VSTS we must be running the latest version of TFS.  Using TFS 2017 is not an option.

**Comment by omarv74** [comment]
@nschonni made a good point. I have not had that issue myself but after looking at the code it does make sense. Have you looked into it? Maybe running the script in PowerShell ISE, set a breakpoint on the 'if' statement or right after it and see what the value of $WitAdminExe is. Or by writing its value with Write-Host. You definitely want to make sure the script is calling the correct version of WitAdmin.exe.
